<?php
/**
 * implements hook_menu()
 */
function confirm_form_example_menu() {
	$items = array();
	
	$items['example/list'] = array(
		'title' => 'Test list',
		'page callback' => 'example_list',
		'access callback' => TRUE,
	);
	
	$items['example/%/delete'] = array(
		'title' => 'Delete item',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('example_delete', 1),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}

function confirm_form_example_list() {
	$header = array('#', 'Item', 'Action');
	$rows = array(
		array(1, 'Apple', l('Delete', 'example/1/delete')),
		array(2, 'Android', l('Delete', 'example/2/delete')),
		array(3, 'Blackberry', l('Delete', 'example/3/delete')),
	);
	
	return theme('table', array('header' => $header, 'rows' => $rows));
}

function confirm_form_example_delete($form, &$form_state, $the_id) {
	$form = array();
	$form['the_id'] = array(
		'#type' => 'value',
		'#value' => $the_id,
	);
	
	return confirm_form(
		$form,
		t('Are you sure you want to delete this item?'),
		'example/list',
		t('This action cannot be undone.'),
		t('Delete'),
		t('Cancel')
	);

	return $form;
}

/**
 * submit handler for the example_delete
 * this function is invoked only when the user clicks confirm button
 * clickin on cancel, the user goes back to the $path
 */
function confirm_form_example_delete_submit($form, &$form_state) {
	//dpm($form_state['values']);
	
	if ($form_state['values']['the_id'] == 1) {
		// do some this here
	}
	
	drupal_set_message('You confirmed item ' . $form_state['values']['the_id'] . '.');
	$form_state['redirect'] = 'example/list';
}
